### ISSUE TITLE
Delta and Main

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#12]
Hello dear,

the delta indexing is not being readed/searched by the vbulletin search, i can find new posts in search only after running the main, any idea why the delta is not working although it's indexing successfully?

**Comment by puzrin** [comment]
1. At first, I'd recommend to install sphinx 1.11 from trunk. It's much better than 1.10beta.
2. Post your changed config files to gists and give me links
3. Use sphinx command-line tool to search in delta. Make sure, that data is really indexed. If your dbtables have prefixes, we coud miss somerthing - havent tested this.

We should understand, is this problem in sphinx, addon indexer or addon searcher. Let me know results.

**Comment by danswano** [comment]
Problem solved, the cron was unable to run delta due to php error and it fixed by adding php -q inside the config file.

Also installed 1.11 as you recommended, thank you very much.

One question: real time indexing possible with your product?

**Comment by puzrin** [comment]
RT will be available as soon as RT indexes will support MVA. Without MVA it's difficult to do tag search (i know, it's broken right now).

**Comment by danswano** [comment]
No problem, nice mod indeed, keep up the good work.
