### ISSUE TITLE
code review fixes, part 3 [ERROR]

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#14]
Parse error: syntax error, unexpected T_IF in /home/user/public_html/forum/packages/vbsphinxsearch/coresearchcontroller.php on line 584

**Comment by puzrin** [comment]
1. Install latest version, we've broken code by mistake.
2. Rebuild indexes

Please, note, that more updates will come tommorow

**Comment by danswano** [comment]
Please explain further, you mean i should get the latest sphinx from trunk?

**Comment by puzrin** [comment]
I've just updated sources https://github.com/rcdesign/vb-sphinx_search . Previous version was broken by mistake.

**Comment by danswano** [comment]
Problem solved, i have an addiction these days on your product, i just love it and keeps updating it like crazy by the second. :)

Thank you.
