### ISSUE TITLE
VB Sphinx Products

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#15]
Hello, i saw a paid product somewhere and i would like to ask for permission if we can discuss it and compare it to yours and see if they have better features so you can consider them in future.

If you mind such thing please close this issue and ignore it.

Thanks.

**Comment by puzrin** [comment]
danswano, problem is not that i don't know how to make a good product, but in lack of time / programmers. So, features are limited to "can't leave without" set. If someone wish to join, of base his own addon on my sources - that's doesn't need special discussion or my permission.

If you know qualified programmers, who are interested to improve this code - advice them to join here. Github is very convenient place to collaborate efforts.

**Comment by danswano** [comment]
I just wanted to help in giving ideas or something, sadly i don't know programmers and i'm not one of them too but i appreciate your efforts in this product and i want it to be the best for all. :)
