### ISSUE TITLE
Sphinx 2.0.1-beta error

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#18]
Sphinx 2.0.1-beta is out and after installing it and running the search daemon using the config file i get this error:

Sphinx 2.0.1-beta (r2792)
Copyright (c) 2001-2011, Andrew Aksyonoff
Copyright (c) 2008-2011, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/usr/local/etc/sphinx-conf.php'...
WARNING: compat_sphinxql_magics=1 is deprecated; please update your application and config

Will reindexing solve this problem or i should wait for an updated version of vb-sphinx_search?

Thanks. :)

**Comment by puzrin** [comment]
1. failed to lock pid file - that means, sphinx is already running. make sure to kill sphinx processes.
2. I have't tested code with 2.0.1, and not sure that will. Switched to develop my own forum https://github.com/nodeca

**Comment by danswano** [comment]
Sorry i did notice the pid error after posting but the product is working, it's just throw this error when executing the daemon

WARNING: compat_sphinxql_magics=1 is deprecated; please update your application and config.

Anyway if it didn't work well for me  i will switch back to 1.11, thank you very much. :)

You are not developing your own forum engine :o, is that for real? you will give up all available software and make yours?

**Comment by ECBINET** [comment]
Okay,
at first, you should to check config file, such as sphinx.config.in, check if "@CONFDIR@" has been replaced to correct place, for example, "C:\Servers\Sphinx\log/query.log", etc.
second, view the log file, have any error info show you? such as, my log file show me: "[Tue Jun  7 18:49:04.869 2011] [  708] FATAL: failed to open query log file './log/query.log': No such file or directory".
Okay, fix it, retry to start SphinxSearch, googd luck!
