### ISSUE TITLE
Executing error 

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#19]
Hello, when i run the flowing command:

/usr/local/bin/searchd --config /usr/local/etc/sphinx-conf.php

i get this error:

ERROR: error executing '/usr/bin/php5 -q', killed by signal 11 in
/usr/local/etc/sphinx-conf.php line 1 col 1.
FATAL: failed to parse config file '/usr/local/etc/sphinx-conf.php'

any fix for this error?

**Comment by puzrin** [comment]
Sorry, vb-related projects are not supported. This code is published as is.
